spring:
  datasource:
    url: jdbc:h2:file:./data/budgetlog   # ./data/budgetlog.mv.db 파일 생성됨
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console   # http://localhost:8888/h2-console

  jpa:
    hibernate:
      ddl-auto: update    # 기존 테이블 유지하면서 변경만 반영
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  #token: budget-log-secret-key-2025-05-27
  token: Kdn49s8Jwq0XfP3GmV6qP5ZcL9aMb2qTiR4wU7c2bFE=
  expire:
    access: 3600000 # 1 hour
    refresh: 604800000 # 7 days