spring:
  application:
    name: budgetlog
  datasource:
    url: jdbc:mariadb://localhost:3306/budgetlog
    username: budgetlog
    password: budgetlog
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:/database/schema.sql

server:
  port: 8080
  servlet:
    context-path: /