spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/budgetlog
    username: budgetlog  # MariaDB 사용자명
    password: budgetlog  # MariaDB 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.MariaDBDialect

jwt:
  #token: budget-log-secret-key-2025-05-27
  token: Kdn49s8Jwq0XfP3GmV6qP5ZcL9aMb2qTiR4wU7c2bFE=
  expire:
    access: 3600 # 1 hour
    refresh: 604800 # 7 days

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE