spring:
  datasource:
    url: jdbc:h2:mem:budgetlogdb # 인메모리 H2 DB URL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # formatSql -> format_sql (표준 YAML 키 형식)
        dialect: org.hibernate.dialect.H2Dialect # H2 방언으로 변경
  h2:
    console:
      enabled: true # H2 콘솔 활성화
      path: /h2-console # 콘솔 접속 경로

jwt:
  #token: budget-log-secret-key-2025-05-27
  token: Kdn49s8Jwq0XfP3GmV6qP5ZcL9aMb2qTiR4wU7c2bFE=
  expire:
    access: 3600 # 1 hour
    refresh: 604800 # 7 days