spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/budgetlog
    username: budgetlog
    password: budgetlog
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.MariaDBDialect

jwt:
  #token: budget-log-secret-key-2025-05-27
  token: Kdn49s8Jwq0XfP3GmV6qP5ZcL9aMb2qTiR4wU7c2bFE=
  expire:
    access: 3600 # 1 hour
    refresh: 604800 # 7 days